### ISSUE TITLE
does this project still alive?

### ISSUE THREAD

**Issue by dextercai** [Hans0924/Echo_Console#1]
does this project still alive?
l am interested the protocol of fsd, do you know some details of FSD?

**Comment by Hans0924** [comment]
Hi,
    This is just a console tool to test some FSD protocols. As I am working on fully functional version of ECHO Pilot Client now, this project will not be updated.
    There is little information about FSD protocols, so I have to do some guess work from captured data. I think it's a better idea to ask VATSIM or IVAO for protocols, but they may not allow you to use their protocols on your own FSD server.

Hans

**Comment by dextercai** [comment]
thanks for reply, will your echo pilot client will also open sorce on github?

**Comment by Hans0924** [comment]
That has not been decided yet. I am willing to share my code with FS players & developers. However, you may know that there are so many FS sites or platforms in the Internet. Some of these sites steal code (sorry for using this word, but they did it.) from other sites. So I don't think they will follow open source license either.
I will consider this later. Thanks for your interests anyway.

Hans

**Comment by dextercai** [comment]
l know what you mean. Thanks for your reply patiently.

**Comment by Hans0924** [comment]
I will close this issue. BTW, I am a Chinese too. 😊
